### ISSUE TITLE
[DOCS] README and Contribution Files / Code of Conduct

### ISSUE THREAD

**Issue by danielnewell** [amethyst-studio/k-value#2]
Allow @danielnewell to make a read me.

**Comment by danielnewell** [comment]
And other contribution files

**Comment by xCykrix** [comment]
Do you still wish to perform this task? Also, official documentation is available at

https://amethyst-studio.github.io/K-Value/index.html

**Comment by xCykrix** [comment]
Reassigned to me due to time contraints.

**Comment by xCykrix** [comment]
Closed by #8. Didn't link for some reason.
