### ISSUE TITLE
[DOCS] Documentation and Wiki Page

### ISSUE THREAD

**Issue by xCykrix** [amethyst-studio/k-value#7]
**Is your feature request related to a problem? Please describe.**
No documentation currently present.

**Describe the solution you'd like**
Integrated API Documentation and examples via the Wiki.

**Describe alternatives you've considered**
N/A

**Additional context**
https://amethyst-studio.github.io/k-value/index.html

**Comment by ghostdevv** [comment]
Wiki as in github wiki or a external site?

**Comment by xCykrix** [comment]
It will be using the GitHub Wiki @ghostdevv. I'm working on a lot of this stuff at the moment, as I am doing #2 which is the start of this.

**Comment by ghostdevv** [comment]
Oki sounds good @xCykrix

**Comment by xCykrix** [comment]
The wiki page is partially implemented. A new issue will be introduced to follow up on adding documentation regarding contributing adapters and creating custom adapters with our API.
